### ISSUE TITLE
A problem for the metrics used in the paper

### ISSUE THREAD

**Issue by showgood163** [yhlleo/DWC-GAN#2]
Hi there!

Considering that the metrics you provided (IS, FID & LPIPS) and [how versatile they are](https://arxiv.org/pdf/2008.01576.pdf), I think it is very important to know how you evaluate your model. Could you explain them in detail?

Thanks!

**Comment by yhlleo** [comment]
Thanks for your suggestion. I'm busy on something else recently. I'll prepare the detailed documents and codes for everything soon.

**Comment by yhlleo** [comment]
@showgood163, we have released the evaluation codes in this repo: [GAN-Metrics](https://github.com/yhlleo/GAN-Metrics). If you have any problems, please let me know.
