### ISSUE TITLE
pretrain embedding

### ISSUE THREAD

**Issue by jinjiujiujin** [yhlleo/DWC-GAN#6]
Hello! May I ask How do you train the text embedding? I want to use the project for my dataset, but I am not sure how to train the embedding.

**Comment by yhlleo** [comment]
@jinjiujiujin 

Hi! I uploaded a scripts [`tools/build_embeddings.py`](https://github.com/yhlleo/DWC-GAN/blob/master/tools/build_embeddings.py), where an example is provided to collect the pre-trained embeddings from [`fastText`](https://github.com/facebookresearch/fastText).
