### ISSUE TITLE
How to evaluate FID?

### ISSUE THREAD

**Issue by jinjiujiujin** [yhlleo/DWC-GAN#7]
Hello! Sorry to bother you. I trained the model based on the released code, and I am trying to evaluate the FID of my model. According to the paper, I randomly selected 10000 source images and 10000 target images from celeba dataset, and generated the images based on the target attribute, but my FID score is about 20, much lower than the paper(32.14). 
I am wondering if there is something wrong with the way I choose pictures? 
I used the code in [https://github.com/MinfengZhu/DM-GAN](https://github.com/MinfengZhu/DM-GAN) to calculate FID.

**Comment by yhlleo** [comment]
Hi @jinjiujiujin, it could be the  differences between evaluation image sets. I added the resources for the FID evaluation: https://github.com/yhlleo/DWC-GAN/tree/master/valid/FID-IS. 

 - [src2trg](https://github.com/yhlleo/DWC-GAN/blob/master/valid/FID-IS/src2trg_celeba-1e4-overall.lst): the input source image and text. 
 - [trg](https://github.com/yhlleo/DWC-GAN/blob/master/valid/FID-IS/trg_celeba-1e4.lst): the images in the target domains for FID.

If you have any questions, please let me know.
